display:
  mach: 3
  unit:
    name: "mph"
    factor: 2.23694
pyxcel:
  repository: "/opt/pyxcel"
quarkus:
  http:
    host: 0.0.0.0
    port: 8080
  log:
    category:
      "cn.zzm":
        level: "DEBUG"